version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - DEBUG=False
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  
  api:
    image: "webserver:latest" # Change to .softhsm to enable hsm service
    build:
      context: .
      dockerfile: docker/Dockerfile.webserver
    depends_on:
      - postgres
    ports:
      - 8000:8000