version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      - DEBUG=False
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - dot-net
    ports:
      - "5432:5432"

  api:
    image: "webserver:softshm"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - ENV_STATUS=DEBUG
      - DEBUG=True
    volumes:
      - ./api/service/softhsm_client:/api/service/softhsm_client
    build:
      context: .
      dockerfile: docker/Dockerfile.softhsm
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - dot-net

networks:
  dot-net:


volumes:
  db_data:
