openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /service/login:
    post:
      description: |
        To get login to the system - will get the access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username
                password:
                  type: string
                  description: Password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_code:
                    type: string
                    description: Code Access to request to another endpoint
  /service/gen_key:
    post:
      description: |
        OK
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_key:
                    type: string
                    description: Code Access to request to another endpoint
                  key_id:
                    type: string
                    

