# Generated by Django 3.2.8 on 2022-05-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('public_key', models.CharField(help_text='Generated Public Key', max_length=1000, verbose_name='Public Key')),
                ('hsm_label', models.IntegerField(verbose_name='Generated ID/Label Key from softhsm')),
                ('key_type', models.CharField(choices=[('RSA', 'RSA Key'), ('ECDSA', 'ECDSA Key')], max_length=50)),
                ('user', models.OneToOneField(help_text='User initiate the key generation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='softhsm_client.key')),
                ('user', models.OneToOneField(help_text='User who create this certificate', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified'],
                'abstract': False,
            },
        ),
    ]